version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  test-build-scan:
    docker:
      - image: cimg/node:17.9.0
    resource_class: small

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
      - run:
          command: npm run build
          name: Build app
      - sonarcloud/scan
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy-dev:
    docker:
      - image: cimg/node:17.9.0
    resource_class: small
    
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          api-key: HEROKU_API_KEY
          app-name: $DEV_HEROKU_APP_NAME
          branch: dev
          force: true

  deploy-prod:
    docker:
      - image: cimg/node:17.9.0
    resource_class: small
    
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          api-key: HEROKU_API_KEY
          app-name: $PROD_HEROKU_APP_NAME
          branch: main
          force: true

workflows:
  build-deploy:
    jobs:
      - test-build-scan:
          context: SonarCloud
      - deploy-dev:
          requires:
            - test-build-scan
          filters:
            branches:
              only: dev
      - deploy-prod:
          requires:
            - test-build-scan
          filters:
            branches:
              only: main